### ISSUE TITLE
Server error on log in

### ISSUE THREAD

**Issue by n-greene** [dgmid/nextcloud-bookmark-manager#22]
I just installed the latest version 2.05

Log in with succesful 2fa

Error: Cannot read property &#39;find&#39;of null
![Screen Shot 2020-07-30 at 5 13 05 PM](https://user-images.githubusercontent.com/69021244/88986834-efdf5e80-d288-11ea-84b5-61d96a9301c5.png)

**Comment by dgmid** [comment]
Can you have a look in the log file and see if there is anything else there?
You can find it here:

~/Library/Logs/Nextcloud Bookmark Manager/renderer.log

**Comment by n-greene** [comment]
Hi - There does not seem to be a log file at all.

**Comment by n-greene** [comment]
Ok nevermind:

/Users/nic/Library/Logs/Nextcloud Bookmark Manager/main.log
[2020-08-02 10:22:00.213] [info] main window is not responding…
[2020-08-02 10:22:33.057] [info] main window is responding

/Users/nic/Library/Logs/Nextcloud Bookmark Manager/renderer.log
[2020-07-30 17:12:53.368] [info] all :
/index.php/apps/bookmarks/public/rest/v2/bookmark?page=-1
[2020-07-30 17:12:54.212] [info] response ok
[2020-07-30 17:12:54.300] [error] {
  constructor: 'TypeError',
  stack: "TypeError: Cannot read property 'find' of null\n" +
    '    at parseBookmarks (/Applications/Nextcloud Bookmark
Manager.app/Contents/Resources/app.asar/dist/js/app.min.js:106:31)\n' +
    '    at /Applications/Nextcloud Bookmark
Manager.app/Contents/Resources/app.asar/dist/js/app.min.js:623:3\n' +
    '    at /Applications/Nextcloud Bookmark
Manager.app/Contents/Resources/app.asar/dist/js/fetch.min.js:135:6'
}
[2020-08-02 10:21:24.544] [info] folders :
/index.php/apps/bookmarks/public/rest/v2/folder
[2020-08-02 10:21:25.231] [info] response ok
[2020-08-02 10:21:25.253] [info] all :
/index.php/apps/bookmarks/public/rest/v2/bookmark?page=-1
[2020-08-02 10:21:25.900] [info] response ok

**Comment by dgmid** [comment]
Can you let me know what version of the Bookmarks app you have installed in your Nextcloud?

**Comment by n-greene** [comment]
Latest, 3.3.3

**Comment by n-greene** [comment]
Still having same error with version 3.3.4

**Comment by bunducafe** [comment]
+1 
And I am now on 4.0.5 with the NC bookmark app.

**Comment by Marschhuber** [comment]
Hi! I tried your app for the first time and I'm getting the same error. Will you fix it?
I'n now on NC Bookmark App V. 4.0.8 on Nextcloud 20

**Comment by emce** [comment]
Same for me.
<img width="1000" alt="Zrzut ekranu 2021-11-8 o 12 03 57" src="https://user-images.githubusercontent.com/842099/140731576-4df8fec9-b153-4873-95ad-74a41ccbcf04.png">

**Comment by bunducafe** [comment]
It seems a bit that the maintainer has not the time anymore to get this done. I am already away from it and sync my bookmarks again via Floccus to Nextcloud and vice versa... All the modification is done then within Firefox itself.

**Comment by onkelbeh** [comment]
Same here, v2.0.5 from Github, nextcloud-21.0.7:

```
[2021-12-29 07:59:23.538] [info] all : /index.php/apps/bookmarks/public/rest/v2/bookmark?page=-1
[2021-12-29 07:59:23.688] [info] response ok
[2021-12-29 07:59:23.694] [error] {
  constructor: 'TypeError',
  stack: "TypeError: Cannot read property 'find' of null\n" +
    '    at parseBookmarks (/Applications/Nextcloud Bookmark Manager.app/Contents/Resources/app.asar/dist/js/app.min.js:106:31)\n' +
    '    at /Applications/Nextcloud Bookmark Manager.app/Contents/Resources/app.asar/dist/js/app.min.js:623:3\n' +
    '    at /Applications/Nextcloud Bookmark Manager.app/Contents/Resources/app.asar/dist/js/fetch.min.js:135:6'
}
[2021-12-29 08:01:01.682] [info] all : /index.php/apps/bookmarks/public/rest/v2/bookmark?page=-1
[2021-12-29 08:01:01.789] [info] response ok
[2021-12-29 08:01:01.792] [error] {
  constructor: 'TypeError',
  stack: "TypeError: Cannot read property 'find' of null\n" +
    '    at parseBookmarks (/Applications/Nextcloud Bookmark Manager.app/Contents/Resources/app.asar/dist/js/app.min.js:106:31)\n' +
    '    at /Applications/Nextcloud Bookmark Manager.app/Contents/Resources/app.asar/dist/js/app.min.js:623:3\n' +
    '    at /Applications/Nextcloud Bookmark Manager.app/Contents/Resources/app.asar/dist/js/fetch.min.js:135:6'
}
```

**Comment by onkelbeh** [comment]
Perhaps, as an idea: I have a lot of entries (for the bar) without title, only with an icon.

**Comment by relink2013** [comment]
Im seeing this exact issue. Is there any possibility of a fix? This app looks perfect for my use.

**Comment by bunducafe** [comment]
I think that this project is rather abandoned. So I stick with the Floccus plugin which works fairly well within my setup.
